{
 "title": "MyDasboard",
 "time": { "from": "2022-04-07T09:29:39.535Z", "to": "2022-04-07T09:49:39.535Z" },
 "panels": [
  {
   "title": "Свободная память",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes/1024/1024/1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Свободное место на диске",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\"}/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Средняя нагрузка 1 м (LA1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Средняя нагрузка 5  м (LA5)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Средняя нагрузка 15 м (LA15)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}