version: '3.1'
networks:
  db_network:
    driver: bridge
services:
  mydb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: testmysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin 
    volumes:
      - ./mdata:/var/lib/mysql
      - ./backup:/backup
    networks:
      - db_network
    ports:
      - 3306:3306





